### ISSUE TITLE
The JSON response from the API could not be parsed

### ISSUE THREAD

**Issue by Nic1911** [d4l-data4life/kirby3-static-site-generator#29]
Hi guys, this is an help request for an error on static-site-generation request.

## Expected Behavior
`static` folder generation with the static files.

## Current Behavior
I've this error in the panel `The JSON response from the API could not be parsed. Please check your API connection.`, while in network tab I  have a `Status Code: 302 Found`

<img width="1424" alt="Schermata 2020-07-14 alle 21 52 41" src="https://user-images.githubusercontent.com/16899631/87470006-6d199b00-c61c-11ea-84fc-6d4bdb2b7fd9.png">

## Steps to Reproduce

Here my config options
'd4l' => [
        'static_site_generator' => [
          'endpoint' => 'generate-static-site', 
          'output_folder' => './static', 
          'preserve' => [], 
          'base_url' => '/',
          'skip_media' => false,
          'skip_templates' => [] 
        ]
    ],

## Context
Kirby version 3.0
Additional plugins:
"diverently/laravel-mix-kirby": "^1.1",
"bnomei/kirby3-autoid": "^1.4",
"mzur/kirby-uniform": "^4.0",
"bnomei/kirby3-janitor": "^1.4",
"bvdputte/kirby-log": "^1.0",
"sylvainjule/previews": "^1.0",
"rasteiner/k3-pagesdisplay-section": "^0.0.5"

Many thanks!

**Comment by jonathan-reisdorf** [comment]
Hi @Nic1911, thanks for reporting! Can you please try if it works now with the latest version of the plugin?

**Comment by Nic1911** [comment]
Hi @jonathan-reisdorf, I've just tried your last release.
Unfortunately the response is an error related to Kirby Uniform plugin: "The CSRF token was invalid".

After that I've disabled the plugin, but the error doesn't seem to be resolved...
The difference I can notice seems to be the api status 500.

<img width="1434" alt="Schermata 2020-08-05 alle 23 19 24" src="https://user-images.githubusercontent.com/16899631/89465450-69d48380-d772-11ea-93a2-eda91d937cc6.png">

Thanks for your support! 🙏

**Comment by bensanlau** [comment]
Hi @Nic1911, I also ran into a similar error message while deploying locally. My terminal console gave me the error: `PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /Users/.../my-project/vendor/claviska/simpleimage/src/claviska/SimpleImage.php on line 249`

I set a time limit of 60seconds in my deployment, and it generated successfully. Hopefully it works for you, too.

**Comment by Nic1911** [comment]
Hi @bensanlau, could you give me a further example how to set a time limit, please? I'm not skilled enough on php 😩.
Thanks a lot!

**Comment by jonathan-reisdorf** [comment]
@Nic1911 you can adapt this timeout with the `max_execution_time` setting.
https://www.php.net/manual/en/info.configuration.php#ini.max-execution-time

Depending on your php installation the recommended way to change this value differs. If you have an extremely simple setup, you can simply adjust the value in your `php.ini`, but if you used a package manager to install php, this might add complications when updating your php installation later.

PHP also allows you to have additional, separate ini files for further configuration. Depending on your installation there might be a `conf.d` folder or, e.g. if you're using php-fpm, you can also adjust ini settings via your pool.d conf files.

As a quickfix, it might also work to dynamically set the timeout dynamically (runtime) with `ini_set`.

**Comment by jonathan-reisdorf** [comment]
Please let me know if you need further advice. For now I'll assume that the issue is solved.

**Comment by Nic1911** [comment]
I'm really sorry for the delay @jonathan-reisdorf. 
I've tried adapting the max_execution_time setting on 60 as suggested, but it still doesn't works. 
The error message is the same: "The JSON response from the API could not be parsed. Please check your API connection.".
Any other idea?

In the picture you can see the error  in the console, hope it's can be useful.
<img width="1437" alt="Schermata 2020-09-08 alle 17 58 12" src="https://user-images.githubusercontent.com/16899631/92500200-1c2db980-f1fd-11ea-8623-8284533f5c8f.png">
<img width="1438" alt="Schermata 2020-09-08 alle 17 58 24" src="https://user-images.githubusercontent.com/16899631/92500213-20f26d80-f1fd-11ea-9727-b692f2fe0ad8.png">



Thank you

**Comment by jonathan-reisdorf** [comment]
Thanks for the answer. To further debug into the issue, you'd need to have a look at the Response tab of the network request, please (in your screenshot that would be the "Risposta" tab on the right side). This one should give you more details about the issue that occurred. Then, depending on that, you'll either need to increase the max execution time to an even higher number or there's another error. By the way, when updating to the latest version of the static site generator plugin, rebuilding the static site should be much faster after the first time.

**Comment by Nic1911** [comment]
Hi @jonathan-reisdorf, after update to the latest version the operation is successful 💪
Many thanks for your patience and your support.
